### ISSUE TITLE
Vaadin OSGi applications should not expose relevant classpath content as static resources

### ISSUE THREAD

**Issue by mstahv** [vaadin/osgi#50]
In our OSGi examples (https://github.com/vaadin/base-starter-flow-osgi & https://github.com/vaadin/base-starter-flow-karaf) class files and other resources can be accessed from the main bundles. This is unexpected behaviour from the end users point of view and can be considered a bad practise.

We should either change the implementation of our integration code so that generic content from bundle(s) is not served or change the examples so that only minimal and security wise safe content is exposed.

If we only change our examples, it should be documented that all resources (including class files) from the bundle that is registering the servlet are exposed.

**Comment by denis-anisimov** [comment]
This is partially an issue in overall OSGi HTTP whiteboard implementation (not sure about specification) and Vaadin:
- all the resources located inside the bundle/jar (except specific paths like `META-INF` ) are available via a `ServletContext`  for the Servlet registered in the bundle. This is behavior of HTTP whiteboard.
- any resource available in the Servlet context is exposed via HTTP by the `VaadinServlet` (namely `StaticFileServer`).

Vaadin behavior is the same regardless servlet container. But the first behavior is quite specific for OSGi: one has to do an explicit action/configuration to include resources available via `ServletContext`.

Unfortunately there is no easy way to fix this: if we disable serving resources available via `ServletContext` by the static file server many existing WAR applications will be broken since they rely on this existing functionality.
But this is what should be done for the OSGi case: prevent serving resources available via `ServletContext` (at least partially).

In fact there is already existing solution for this (even though it's not obvious that it's always "required" with Vaadin): a custom `ServletContextHelper`.
A custom `ServletContextHelper` may be registered as a service and it may decide which resources should be in the `ServletContext` and which should not be. Then the servlet should be registered using a specific property to select the specific context.

So there is already a solution for this but it requires additional class and complicates the servlet registration: every servlet should be registered using some `ServletContextHelper` (and we can't do this automatically since we don't know which context path to use).

On the other hand it's quite easy to expose any classpath resource via Resource service, so there is no need to expose automatically everything available via `ServletContext` by the `VaadinServlet`.
So I think we can disable in OSGi case exposing resources from the `ServletContext`.

**Comment by denis-anisimov** [comment]
>you have to explicit register an Service that uses special service properties.
I agree with you.

But by sentence says totally different thing.
It says that the resources in the Jar becomes available as a resource in the `ServletContext` which means if you use method `ServletContext::getResource(String)` then it will return a URL for any resource inside bundle/jar (except ....).
And yes, to be able to access to the resource via WEB one has to register a resource service.
But one thing is access to the resource via WEB and another thing is access to the resource via `ServletContext`.

**Comment by pleku** [comment]
> all the resources located inside the bundle/jar (except specific paths like META-INF ) are available via a ServletContext for the Servlet registered in the bundle. This is behavior of HTTP whiteboard.

@denis-anisimov it seems that the `META-INF/MANIFEST.MD` can be accessed via the browser, so could you clarify what you meant with the _except specific paths like META-INF_ part ?

**Comment by denis-anisimov** [comment]
The sentence targets the resources availability via `ServletContext` and `META-INF` part was just a note.
I've tried to access to some resource inside `META-INF`  and wasn't able to access.

**Comment by pleku** [comment]
Ok. Both me and Artem were able to access the manifest file. I'll edit the comment so nobody has any misunderstanding.
