### ISSUE TITLE
Update karaf to 4.4.0

### ISSUE THREAD

**Issue by caalador** [vaadin/osgi#90]
At the moment the karaf tests are compatible with karaf 4.3.7.
An investigation should be made into why karaf 4.4.0 doesn't install the `<bundle>mvn:com.helger.commons/ph-commons/10.1.6</bundle>` even though it is in `feature.xml` generated in karaf-test-project.

**Comment by jochenwalz** [comment]
The ph-commons bundle doesn't resolve because Karaf's war feature in 4.4.0 (and the pax-web features it depends upon) does not drag in the org.apache.aries.spifly.dynamic.bundle bundle any longer. When explicitly installing it (and adapting the settings in org.ops4j.pax.web.cfg according to the changes in pax-web 8), all bundles resolve. However, there is an error on startup, see [https://github.com/vaadin/osgi/issues/93](https://github.com/vaadin/osgi/issues/93).

**Comment by mcollovati** [comment]
Not sure if it relates with this issue, but the karaf example seems to work with 4.4.0 and some changes in maven plugin configuration

See https://github.com/vaadin/vaadin-flow-karaf-example/issues/65#issuecomment-1125153463 for details

**Comment by jochenwalz** [comment]
Yes, when adding the felix-http feature, it somehow works. However, that really looks like a workaround, because with felix-http and the war feature installed, there are port conflicts according to the karaf.log file. When adding the Web-ContextPath to bnd.bnd and omitting the felix-http feature, Pax-Web detects main-ui as Web application bundle, but then the null pointer exception occurs in the OSGiResourceProvider of the flow-osgi bundle.

**Comment by mcollovati** [comment]
It seems to work after adding following features: http-whiteboard,scr,spifly
